#!/usr/bin/env ruby
# frozen_string_literal: true

require "yaml"
require "fileutils"

ROOT = File.expand_path("..", __dir__)
DATA_FILE = File.join(ROOT, "_data", "poster.yml")
GENERATED_MARKER = "# generated by script/generate_poster_pages.rb"

def load_categories
  data = YAML.load_file(DATA_FILE)
  data["categories"] || []
end

def yaml_value(value)
  value.to_s.match?(/[:#\n]/) ? value.to_s.inspect : value.to_s
end

def write_page(path, front_matter)
  dir = File.dirname(path)
  FileUtils.mkdir_p(dir)

  body = +"---\n"
  body << "#{GENERATED_MARKER}\n"
  front_matter.each { |key, value| body << "#{key}: #{yaml_value(value)}\n" }
  body << "---\n"

  File.write(path, body)
end

categories = load_categories
expected = []

categories.each do |cat|
  slug = cat["slug"]
  title = cat["title"]
  cat_index = File.join(ROOT, "poster", slug, "index.md")
  expected << cat_index

  write_page(
    cat_index,
    {
      "layout" => "poster-category",
      "title" => title,
      "description" => "#{title} 카테고리 Poster 글 모음",
      "category" => slug,
      "permalink" => "/poster/#{slug}/"
    }
  )

  next unless cat["subcategories"].is_a?(Array)

  cat["subcategories"].each do |sub|
    sub_slug = sub["slug"]
    sub_title = sub["title"]
    sub_index = File.join(ROOT, "poster", slug, sub_slug, "index.md")
    expected << sub_index

    write_page(
      sub_index,
      {
        "layout" => "poster-category",
        "title" => sub_title,
        "description" => "#{sub_title} 알고리즘 Poster 글 모음",
        "category" => slug,
        "subcategory" => sub_slug,
        "permalink" => "/poster/#{slug}/#{sub_slug}/"
      }
    )
  end
end

Dir.glob(File.join(ROOT, "poster", "**", "index.md")).each do |path|
  content = File.read(path)
  next unless content.include?(GENERATED_MARKER) || content.start_with?("<!-- generated by script/generate_poster_pages.rb")
  next if expected.include?(path)

  FileUtils.rm_f(path)
  dir = File.dirname(path)
  Dir.rmdir(dir) if Dir.empty?(dir)
end

puts "Generated #{expected.size} poster page(s) from _data/poster.yml"
